### ISSUE TITLE
TR support

### ISSUE THREAD

**Issue by artrag** [santiontanon/talesofpopolon#1]
You could easily add R800 support. This code supports also generic turbo machines 

```

rdslt		equ	0x000c
CALSLT	equ	0x001c
chgcpu	equ	0x0180		; change cpu mode
exttbl	equ	0xfcc1		; main rom slot

; Switch to r800 rom mode
	
_set_r800:
	in	a,(0aah)
	and 011110000B		; upper 4 bits contain info to preserve
	or	6
	out (0aah),a
	in	a,(0a9h)
	ld	l,a		; we skip Turbo if CTRL is pressed
	ld	a,(0x002d)
	cp	3		; this is a TR
	ld	a,l
	jr	z,set_turbo_tr
				; this is something else
	and	0x02		; CTR
	ret	nz		; if NZ, CTR is not pressed set the turbo
	ld	A,(chgcpu)
	cp	0C3h		; if any code is present, try to activate it 
	ld	a,81h		; R800 ROM mode or any other turbo
	call	z,chgcpu
	ret
set_turbo_tr:
	and	0x02		; CTR
	ret	z		; if Z, CTR is pressed -> do not set the turbo
	ld	a,81h		; R800 ROM mode
	jp chgcpu
```

**Comment by sdsnatcher** [comment]
Nice request!

Here's a much shorter version. It uses the Z key and DRAM mode instead.

```
ENATURBO:
	ld	A,5
	call	SNSMAT
	and	080H		; Is Z key pressed?
	ret	z		; Yes, return
ENATURBO2:
	ld	A,(CHGCPU)
	cp	0C3H
	ld	A,82H		; R800 DRAM
	call	z,CHGCPU
	ret
```

If you don't need the Z key to disable the turbo, just use ENATURBO2 and save some precious space. Personally, I don't se any reason to disable the turbo.    :)

**Comment by santiontanon** [comment]
Thanks!!!! I managed to save about 30 - 40 bytes and I added this :) 

Actually, I couldn't decide wether to use Turbo mode to make the game run faster or smoother. So, I have added a new feature that works as follows:
- By default it just runs on Z80 mode
- At any time during game play, you can press "R" to toggle between 3 different game modes:
    - Z80
    - R800 smooth (where the character and the enemies move at the same speed as in Z80 mode, but there is twice as many frames per second, so, movement and rotation look smoother)
    - R800 fast (that works just like Z80 mode but with turbo on, so the game basically just runs about twice as fast).

I want to see if I can save some more bytes to add a small overlay in the screen that tells the player which of the 3 modes is enabled (Z80, R800smooth, or R800fast) for a few seconds and then disappears. But that will be tomorrow.

I haven't updated the release yet, since I want to add a few more things first, but here's a temporary ROM with the latest version: https://dl.dropboxusercontent.com/u/3303662/ToP-turboR-v1.rom

**Comment by sdsnatcher** [comment]
Nice! I just tested it and have some issues to report:

1) The game froze just after I climbed the stairs to the 2nd area

2) Maybe it's a good idea to include speed limiter to a certain max frame rate. I have developed a turbo kit to boost the Panasonic2+ Machines to 10MHz, and the game gets very fast in such configuration.  The GR8Bit can go even faster: 14MHz. If you test the game on openMSX at 14MHz you'll see what I mean.

**Comment by santiontanon** [comment]
True, I just noticed the freezing when climbing the stairs (just fixed it), I broke it when trying to save some bytes for the "pause" functionality :)

I'll add the "speed limiter" to the second batch of "to do" items. After my last push, the only thing left is the compatibility with the Acid2test for releasing a v1.1! 

I'll keep this ticket open until I do the release

Thanks a lot again for all the feedback! :D
